### ISSUE TITLE
Project Refactoring

### ISSUE THREAD

**Issue by shnhrrsn** [tannernelson/vapor-example#10]
Love the idea of Vapor.  I'm a huge fan of Laravel, but since Apple announced Swift would go open source I've wanting to move my web stuff over to Swift, Vapor being based on Laravel is _exactly_ what I've been waiting for.

That being said, I'd like to add support for more Laravel features to Vapor, things like console commands and asset management specifically.  The current directory structure for the example app doesn't really lend itself well to supporting this stuff like this without getting messy fast.

A standard Laravel project looks something like this:

```
app
   Console
      Commands
   Http
      Controllers
      Middleware
   etc...
resources
   assets
   lang
   views
public
```

By using the "Sources" directory right now, everything has to live at a top level due to how Swift PM  works.  If you put "Console" and "Http" subdirectories, you end up with Console and Http modules -- not ideal, especially since code isn't shared between without having to import the module.

Swift PM does let you put subdirectories inside subdirectories in Sources and it won't cascade, so we could do Sources/App/Http, Sources/App/Console, etc.  This basically solves the problem but leaves you with an extra directory.

According to the [Source Layout rules](https://github.com/apple/swift-package-manager/blob/master/Documentation/SourceLayouts.md), if we omit a Sources directory entirely, it builds the root directory as a single module.  This means we could refactor the directory structure to more closely align with Laravel:

```
App
   Console
      Commands
   Http
      Controllers
      Middleware
Resources
Public
```

I'd also like to propose adding a "views" subdirectory to Resources to keep things more organized, since it's a logical place to put asset files that need to be compiled, such as scss.

**Comment by tanner0101** [comment]
Those source layout rules are very interesting. I totally agree with the folder structure you proposed. Would you be able to create a PR that demonstrates this structure?

**Comment by tanner0101** [comment]
Do you think `Console` and `Http` are necessary? I think we could just have `App` and then commands, controllers, middleware, models, etc under that.
