### ISSUE TITLE
building example failed 

### ISSUE THREAD

**Issue by olierxleben** [tannernelson/vapor-example#11]
I tried to build the project, but ran into the following issue:

```
vagrant@vagrant-ubuntu-trusty-64:/vagrant/vapor-example$ swift build
```

```

> warning: refname '0.1.9' is ambiguous.
> warning: refname '0.1.9' is ambiguous.
> warning: refname '0.1.0' is ambiguous.
> warning: refname '0.1.0' is ambiguous.
> /vagrant/vapor-example/Packages/Stencil/Package.swift:6:6: error: type of expression is ambiguous without more context
>     .Package(url: "https://github.com/kylef/PathKit.git", majorVersion: 0, minor: 6),
>     ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> swift-build: exit(1): ["/home/vagrant/swift-2.2-SNAPSHOT-2015-12-01-b-ubuntu14.04/usr/bin/swiftc", "--driver-mode=swift", "-I", "/home/vagrant/swift-2.2-SNAPSHOT-2015-12-01-b-ubuntu14.04/usr/lib/swift/pm", "-L", "/home/vagrant/swift-2.2-SNAPSHOT-2015-12-01-b-ubuntu14.04/usr/lib/swift/pm", "-lPackageDescription", "/vagrant/vapor-example/Packages/Stencil/Package.swift"]

```

I use the following Swift build:

```
Swift version 2.2-dev (LLVM 46be9ff861, Clang 4deb154edc, Swift 778f82939c)
```

**Comment by tanner0101** [comment]
Try removing your Packages and .build folders.

**Comment by olierxleben** [comment]
Following contents after "cleaning" manually: 

> drwxr-xr-x 1 vagrant vagrant  442 Feb 20  2016 ./
> drwxr-xr-x 1 vagrant vagrant  204 Feb 20 21:08 ../
> drwxr-xr-x 1 vagrant vagrant  170 Feb 20 21:08 Deploy/
> -rw-r--r-- 1 vagrant vagrant 1099 Feb 20 21:08 Dockerfile
> drwxr-xr-x 1 vagrant vagrant  442 Feb 20 21:08 .git/
> -rw-r--r-- 1 vagrant vagrant   15 Feb 20 21:08 .gitignore
> -rw-r--r-- 1 vagrant vagrant 1079 Feb 20 21:08 LICENSE
> -rw-r--r-- 1 vagrant vagrant  277 Feb 20 21:08 Package.swift
> -rw-r--r-- 1 vagrant vagrant   27 Feb 20 21:08 Procfile
> drwxr-xr-x 1 vagrant vagrant  136 Feb 20 21:08 Public/
> -rw-r--r-- 1 vagrant vagrant 1986 Feb 20 21:08 README.md
> drwxr-xr-x 1 vagrant vagrant  136 Feb 20 21:08 Resources/
> drwxr-xr-x 1 vagrant vagrant  136 Feb 20 21:08 Sources/
> vagrant@vagrant-ubuntu-trusty-64:/vagrant/vapor-example$ swift build
> Cloning Packages/vapor
> Cloning Packages/vapor-stencil
> Cloning Packages/Stencil
> /vagrant/vapor-example/Packages/Stencil/Package.swift:6:6: error: type of expression is ambiguous without more context
>     .Package(url: "https://github.com/kylef/PathKit.git", majorVersion: 0, minor: 6),
>     ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> swift-build: exit(1): ["/home/vagrant/swift-2.2-SNAPSHOT-2015-12-01-b-ubuntu14.04/usr/bin/swiftc", "--driver-mode=swift", "-I", "/home/vagrant/swift-2.2-SNAPSHOT-2015-12-01-b-ubuntu14.04/usr/lib/swift/pm", "-L", "/home/vagrant/swift-2.2-SNAPSHOT-2015-12-01-b-ubuntu14.04/usr/lib/swift/pm", "-lPackageDescription", "/vagrant/vapor-example/Packages/Stencil/Package.swift"]

Same result. Thanks for help. For the error message I have no idea.

**Comment by tanner0101** [comment]
This looks like an issue with Kylef's `Stencil`. I would try using the latest Swift snapshot (February 8th I believe) that will probably fix it.

Or you could run the Vapor example without Stencil.

**Comment by abbasfaisal** [comment]
I had the same error on Ubuntu 14.04. I got around by commenting the problematic lines inside the Package.swift file and cloning the 'https://github.com/kylef/PathKit.git' myself and doing swift build inside PathKit. Then did the swift build again inside vapor-example and it went ahead.

**Comment by olierxleben** [comment]
I switched to latest Linux DEVELOPMENT release (Feb, 3th). 

> $ swift --version
> Swift version 3.0-dev (LLVM 524cfeb800, Clang f66c5bb67b, Swift c33f2faad2)

Now I get the following when running swift build:

> error: rename error: File exists (17): /vagrant/vapor-example/Packages/vapor -> /vagrant/vapor-example/Packages/vapor-0.1.9

@tannernelson with or without vapor-stencil dependency in Package.swift, I get the same result 
@abbasfaisal I tried this. But did not help. PathKit is building successfully. 

after error I have two directories in Packages/ : vapor/ and vapor-0.1.9/ Why do I have two vapor folders? I do not see any renaming and copy instructions.

**Comment by tanner0101** [comment]
Are you using a VM? If so, you need to update file permissions. There is a closed issue about this. 

If you're not, try removing the Packages and .build folders again.

**Comment by garis-space** [comment]
I had the same problem, use a vagrant without a shared folder. From the machine "vagrant ssh" create a folder "mkdir vapor" clone him repo vapor and fire up swift build.

**Comment by tanner0101** [comment]
Using the `DEVELOPMENT-SNAPSHOT-2016-02-25-a` Swift version, make sure to build and run with the `./run` command now included in the project.

**Comment by tanner0101** [comment]
Going to keep this open in case anyone has problems running Vapor Example:
1. `git pull` Ensure repo is up to date 
2. `swiftenv install`. Ensure you are running the supported snapshot listed in `.swift-version` (check out [swiftenv](https://github.com/kylef/swiftenv))
3. Use `./build` to build. This script has bug fixes for the Swift Package Manger
4. Try to `./clear` before building
5. Make sure your folder permissions are open if you're using a VM `chmod -R 777`

**Comment by tanner0101** [comment]
Update

As per the updated documentation, use the vapor CLI with `vapor build` and `vapor run`.
