### ISSUE TITLE
Fix issues with Vapor 0.1.0

### ISSUE THREAD

**Issue by DK1DA** [tannernelson/vapor-example#2]
Due to upgrading to Vapor 0.1.0 some issues were introduced I've fixed those as well as added a `Deploy to Swifton.me` badge in my fork: https://github.com/swiftonme/vapor-example

Please also consider making it possible to inject a Port e.g. using `Commander` as does github.com/kylef/Curassow-example-helloworld.

Minor adjustments were necessary (e.g. hard-coding port to 8000) to make it be deployable on [Swifton.me](https://swifton.me). I'd be happy to have this badge here and see it running there. Although this project is still very new, momentarily rather a P.o.C and shouldn't be used in a productive environment.

You can check it out by either of those ways:

**Install Swifton.me CLI and deploy via commandline:***

```
npm install -g swifton
swifton deploy https://github.com/swiftonme/vapor-example
```

**Using the One-click deployment:**

```
https://serve.swifton.me/oneclick?repository=https://github.com/swiftonme/vapor-example
```

**By using the HTTP/S API:**
See [https://serve.swifton.me](https://serve.swifton.me).

**Comment by tanner0101** [comment]
Your changes have been merged, thanks. How do you link to different pages on the deployed app? I deployed a server at http://evil-joliot.serve.swifton.me/ but visiting http://evil-joliot.serve.swifton.me/heartbeat rebuilds the app and then returns `Not Found`.

I've also created issue #4 regarding passing the port as an argument.

**Comment by DK1DA** [comment]
Hi, if you've still got your container id you could look into the logs.
As far as I can see the App has been terminated with `SIGABRT`.

```
14:35:19 web.1  | started with pid 199
14:35:43 web.1  | Could not cast value of type 'Swift.Dictionary<Swift.String, Swift.String>' (0x7efc583ff0b0) to 'Swift.AnyObject' (0x7efc583f9078).
14:35:43 web.1  | Server has started on port 8000
14:35:43 web.1  | Press return to stop it.
14:35:43 web.1  | terminated by SIGABRT
14:35:43 system | sending SIGTERM to all processes
```

This is likely related to the error shown in the output. Probably needs some further investigations as it seems like the app has been re-started by foreman correctly.

**Comment by tanner0101** [comment]
@kimar That's definitely it. That's an unfortunate issue I've been seeing with the Linux compiler. `NSJSONSerialization.dataWithJSONObject()` requires an `AnyObject`, but since `Dictionary` is a `struct` it's creating issues with casting.

I'll see if I can do an optional cast instead. Thanks.

**Comment by tanner0101** [comment]
@kimar The port can now be passed as an argument `.build/debug/VaporApp --port=8000`. Because `8000` is already bound on my Mac, I've reverted the default port to `8080`

**Comment by DK1DA** [comment]
Cool, thanks, I'll update the `Procfile` then and add `$PORT`. Just out of curiosity: What's bound to port 8000 on your mac? Must be some 3rd party app as port 8000 is normally available on Mac...

**Comment by tanner0101** [comment]
Ah you're right...Homestead is the culprit.

**Comment by tanner0101** [comment]
I've set it back to port 8000 for the time being so the deploy button works.

**Comment by DK1DA** [comment]
Set port in Procfile here: https://github.com/tannernelson/vapor-example/pull/5

**Comment by DK1DA** [comment]
But I'm still getting a crash when trying to click e.g. JSON.

```
02:59:07 web.1  | started with pid 118
02:59:14 web.1  | fatal error: 'try!' expression unexpectedly raised an error: Vapor.Response.SerializationError.InvalidObject: file /home/buildnode/jenkins/workspace/oss-swift-package-linux-ubuntu-14_04/swift/stdlib/public/core/ErrorType.swift, line 53
02:59:14 web.1  | terminated by SIGILL
02:59:14 system | sending SIGTERM to all processes
```

Hm, also need to look into restarting crashing apps rather than killing the containers completely on my side..probably.

**Comment by tanner0101** [comment]
I fixed the crash in the error handler. (http://ecstatic-pare.serve.swifton.me/json isn't crashing anymore) But the JSON is still failing to serialize. It looks like on Mac/iOS `Dictionary`s are being automatically casted to `NSDictionary`s when passed to the JSON serializers. Linux doesn't support this cast (pure `Dictionary`s are `structs` and don't qualify as an `AnyObject`).

I'll have to do some more research around this.

**Comment by tanner0101** [comment]
I wrote a fallback JSON serializer. No pretty print, but it will work for now.

http://condescending-jang.serve.swifton.me

Linux compiler is giving these errors which I think is a bug:

```
error: cannot convert value of type '[String]' to expected argument type '[Any]'
```
