### ISSUE TITLE
Mustache example shows message "Page not found".

### ISSUE THREAD

**Issue by AnandSuthar** [tannernelson/vapor-example#23]
main.swift does't have any route for "mustache".

**Comment by paulatwilson** [comment]
I believe that Mustache is currently not working in this version of the snapshot. You can always use javascript and compile that way. 

Here is an excellent link on how to use Mustache in the front end: https://www.youtube.com/watch?v=X8wh6_rdqi0

**Comment by tanner0101** [comment]
We'll be adding Mustache support back in on the next snapshot. There are issue with the current one.
