### ISSUE TITLE
error: noSources

### ISSUE THREAD

**Issue by onmyway133** [tannernelson/vapor-example#28]
Hi, I'm following https://vapor.readme.io/docs/hello-world with the Vapor CLI. I can build OK with Xcode 7.3 toolchain `DEVELOPMENT-SNAPSHOT-2016-05-31-a`

`swiftenv version` inside the `hello-world` gives me

```
DEVELOPMENT-SNAPSHOT-2016-05-31-a (set by /Users/khoa/XcodeProject2/hello-world/.swift-version)
```

However, `vapor build` or `swift build` gives error

```
error: noSources("/Users/khoa/XcodeProject2/hello-world/DerivedData")

Need help getting your project to build?
Join our Slack where hundreds of contributors
are waiting to help: http://slack.qutheory.io

Error: Could not build project.
Note: Make sure you are using Swift 3.0 Snapshot 05-31
```

But I can `swift build` this `vapor-example` and run it 🐼

**Comment by tanner0101** [comment]
You need to add empty folders to the `Package.swift` ignore list or delete them before trying to build.
