### ISSUE TITLE
Empty or wrong response when running from within Xcode

### ISSUE THREAD

**Issue by afh** [tannernelson/vapor-example#31]
**Steps to reproduce:**
- Run the vapor-example from within Xcode (I'm using Xcode 7.3.1 with the 20161-06-06 Swift snapshot)
- Browse to [`http://localhost:8080`](http://localhost:8080)

**Expected Behaviour:**
- The welcome.html page is shown

**Actual Behaviour:**
- An empty HTML page is shown

In addition other routes such as  [`http://localhost:8080/mustache`](http://localhost:8080/mustache) and [`http://localhost:8080/localization/es`](http://localhost:8080/localization/es) do not work.

**Comment by loganwright** [comment]
Note for those coming here, add the following to your main.swift file:

``` Swift
#if os(Linux)
let workDir = "./"
#else
var workDir: String {
    let parent = #file.characters.split(separator: "/").map(String.init).dropLast().joined(separator: "/")
    let path = "/\(parent)/.."
    return path
    }
#endif

let app = Application(workDir: workDir)
```

The issue is that Xcode runs in random folder structures, but we can use this workaround.

**Comment by loganwright** [comment]
This should be in latest 👍 thanks for pointing it out @afh
