### ISSUE TITLE
Exclusion of "Tests" in manifest file must be removed to use swift-test

### ISSUE THREAD

**Issue by woolsweater** [tannernelson/vapor-example#41]
There's an exclusion of the "Tests" directory in the example's Package.swift file, which causes a confusing error if one tries to add tests inside such a directory. The swift-test tool simply claims that no tests exist.

Logan Wright indicated [on the Slack channel](https://qutheory.slack.com/archives/general/p1470254216002175) that this is probably a simple oversight.

It would be great for the exclusion to be removed from the default manifest.

**Comment by loganwright** [comment]
Done and done, thanks @woolsweater
