### ISSUE TITLE
Would love example of CRUD

### ISSUE THREAD

**Issue by kylebshr** [tannernelson/vapor-example#9]
I'm sorry if an issue isn't the right place for this! I would personally implement and make a PR for this, but I don't know how — hence the request. 

Anyway, I was hoping to see an example of a resource implementation. In the README for Vapor it mentions a "user" resource with a controller for it, but I would love to see how that actually works. 

Thanks!

**Comment by tanner0101** [comment]
A CRUD example would be great. I will work on this during my next update to the example repo.

Or if you want to contribute, here's a guide for making a PR http://makeapullrequest.com
